version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      CI_ENVIRONMENT: development
      database.default.hostname: db
      database.default.database: control_acceso
      database.default.username: control_user
      database.default.password: control_pass
      database.default.DBDriver: MySQLi

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: control_acceso
      MYSQL_USER: control_user
      MYSQL_PASSWORD: control_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  mysql_data:
